### ISSUE TITLE
Not working in 1.19.3 (and several versions before)

### ISSUE THREAD

**Issue by b8e5n** [dpo/atom-brackets-glow#6]
I cannot manage to get the glowing working. I tried to put the code in my ~/.atom/styles.less, but no luck there. I cannot manage to get other bracket matchers to work either...

Running on Ubuntu 17.04

**Comment by dpo** [comment]
Does #3 help?

**Comment by BenoitPoulet** [comment]
Not working in 1.19.7 even with the toggle

**Comment by dpo** [comment]
I'm using 1.19.7 and it's worked for me in all past versions. Could you post a list of packages that you've installed and the contents of your stylesheet?

**Comment by BenoitPoulet** [comment]
Hello,

Here are the infos :

```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

![capture](https://user-images.githubusercontent.com/2464712/30601034-31ea6e1a-9d61-11e7-9a4f-e5a748434712.PNG)

**Comment by dpo** [comment]
Now open a new file, open the command palette (Shift-Cmd-P), type "glow" and select the `Atom Brackets Glow: Toggle` command. Then start typing something with opening and closing parentheses. What happens?

**Comment by BenoitPoulet** [comment]
Hello,

If i do this, it works !

Can you add this into your README.md ? 
Because it's not documented, or perhaps everybody know this but me :P

Thank you for your help.

**Comment by dpo** [comment]
Done. Enjoy!

**Comment by b8e5n** [comment]
It still does not work for me, I already found that before :(

**Comment by b8e5n** [comment]
I am now 1.19.6, still not working

**Comment by b8e5n** [comment]
Ok, nvm... I removed reinstalled, disabled and reenabled my addons, it is not working... :)

**Comment by dpo** [comment]
Still not working?
